### ISSUE TITLE
Mode selection not working without 5V with Brook board mod

### ISSUE THREAD

**Issue by Kelvinrr** [Crane1195/GCCPCB#4]
It seems without a 5V connection (e.g, using a GC adapter with both USB-A connections plugged) and a Brook board connected via USB and 20-pin connector, attempting to switch controller modes (Ultimate, PM, etc.) doesn't work. 

#### Steps to reproduce

Connect a GCCPCB to a Brook board, connect the GCCPCB via a GC adapter with only one USB connected to the Switch/PC, and attempt to switch to the Ultimate profile by holding B on connect. If reproduced correctly, it'll be on the Melee profile and the Brook board's power LED will be off. 

This was done by me using a GCCPCB2, a PS4+ Brook board and a Mayflash GCC adapter. 

Disconnecting the brook board or connecting both USB plugs on the adapter fixes the issue. 

Questionable if this can be fixed in software but I might as well document it here and maybe someone can take a crack at it.

**Comment by Crane1195** [comment]
I reproduced this error and was able to prevent it by adding a delay upon plugging in using the GameCube mode. I'll be adding this to the release I am working on, and I'll confirm you no longer have the issue before closing the issue.

**Comment by Crane1195** [comment]
Fixed in firmware release v1.209!
